eppoclient/configurationrequestor.go
eppoclient/configurationstore.go
eppoclient/initclient.go

Got a linter warning:
```
[lint: eppoclient/configurationrequestor.go#L20](https://github.com/Eppo-exp/golang-sdk/commit/a3e57949f19747a09dfe730c3b7ebaff8131306f#annotation_4440670782)
copylocks: newExperimentConfigurationRequestor passes lock by value: github.com/Eppo-exp/golang-sdk/eppoclient.configurationStore contains github.com/hashicorp/golang-lru.Cache contains sync.RWMutex (govet)
```
IMO most of the lint warnings are spurious but this one seems useful.

pass configurationStore by reference

---

eppoclient/config.go

Subj.
If baseUrl not set in config, use `https://eppo.cloud/api`

Add baseUrl default value for eppo client

---

.gitignore
Makefile
eppoclient/client.go
eppoclient/client_test.go
eppoclient/configurationrequestor.go
eppoclient/configurationstore.go
eppoclient/configurationstore_test.go
eppoclient/eppoclient_e2e_test.go
eppoclient/initclient.go
eppoclient/rules.go
eppoclient/rules_test.go
eppoclient/value.go

---
labels: mergeable
---
[//]: #  (Link to the issue corresponding to this chunk of work)
Fixes Eppo-exp/eppo#4711
[//]: #  (Why is this change required? What problem does it solve?)
Design Doc: https://www.notion.so/eppo/Feature-Flagging-API-Design-d768a09de1194cebb04ef8af157fda57
[//]: # (Describe your changes in detail)
Updated the `getAssignment` logic to use the **allocation** (variations + exposure) for the matched targeting rule. The API response inserts a default rule that always matches if the experiment does not have any rules.
See the above design doc for details
[//]: # (Please describe in detail how you tested your changes)
- Updated the e2e tests to use new test data for the V2 RAC response.
[//]: # (OPTIONAL)
[//]: # (Add one or multiple labels: enhancement, refactoring, …

Migrate Go SDK to V2 Randomization Endpoint

---

.gitignore
eppoclient/client_test.go
eppoclient/configurationstore.go
eppoclient/eppoclient_e2e_test.go
eppoclient/httpclient.go

running `make lint` on `main` branch had several errors: https://linear.app/eppo/issue/FF-820/fix-lint-errors-and-deprecations-in-golang-sdk
```
➜  golang-sdk git:(lr/ff-820/lint-dep) make lint
golangci-lint run
```

fix lint failures; upgrade deprecate io/ioutils package (FF-820)

---

.github/workflows/golang-lint.yml
.github/workflows/test-sdk.yml
.gitignore
LICENSE
Makefile
README.md
eppoclient/assignmentlogger.go
eppoclient/client.go
eppoclient/client_test.go
eppoclient/configurationstore.go
eppoclient/eppoclient_e2e_test.go
eppoclient/initclient.go
eppoclient/utils.go
eppoclient/value.go

The RAC API has been updated to support typed values for variations - https://github.com/Eppo-exp/eppo/pull/7418
The GoLang SDK must be updated to support consuming these values and returning native types: `string` (including json), `float64` or `boolean`
I haven't written golang since (checks linkedin) 2020 and since then the [language has added support for generics](https://go.dev/doc/tutorial/generics). In the interest of keeping this PR a manageable size and meeting our release deadlines I have not pursued using them, instead using the `Value` struct as a container that is able to hold `string`, `float64` or `boolean` values.
**api changes**
```
+ new functions 
func (ec *EppoClient) GetBoolAssignment(subjectKey string, flagKey string, subjectAttributes dictionary) (bool, error)
func …
```

add Get*Assignment methods with types (FF-757)

---

eppoclient/client.go

feedback from @petzel in the android sdk https://github.com/Eppo-exp/android-sdk/pull/20/files/ddd4e184376d5a11b62a269d644816d5e02ed105#diff-287964a900b019b23d779f2a2a0bddf0fc42e4d8821c3055266a4453abdf5bd9
keeping the `GetAssignment` will let people upgrade to version 2 without breaking changes.

add GetAssignment method back for backwards compatibility

---

Makefile
eppoclient/client.go
eppoclient/eppoclient_e2e_test.go
eppoclient/value.go

Added new shared test cases and found json variation values were not being handled correctly; returning empty strings - https://linear.app/eppo/issue/FF-883/json-variant-type-not-being-handled-in-golang-sdk
renamed `getJSONAssignment` to `getJSONStringAssignment` inline with our changes across SDKs.
through some debugging I discovered that golang was unmarshaling the string encoded json in the `typedValue` field into native golang objects. that means that the existing `switch` statement in `value.go` did not account for it and the default behavior of `Null()` was occurring.
while this is admirable native behavior for json, at this time we are not supporting it and desire to return string encoded json for consistency across SDKs.

bug: fix json variation value handling

---

eppoclient/assignmentlogger.go
eppoclient/assignmentlogger_test.go
eppoclient/client.go
eppoclient/client_test.go
eppoclient/eppoclient_e2e_test.go
eppoclient/value.go

Enable serialization of `AssignmentEvent` struct which is blocked on being unable to unmarshal the `Value` struct as this handler does not exist.
https://linear.app/eppo/issue/FF-1382/add-serialization-to-go-iassignmentlogger
Adds support for marshalling and unmarshalling the `Value` struct.
**known deficiencies**
`SubjectAttributes` is being marshaled to a string in all cases; need to convert this to a `map[string]Value` to preserve type.

Add marshaling and unmarshaling of Value struct (FF-1382)

---

eppoclient/eppoclient_e2e_test.go
eppoclient/initclient.go

```
--- FAIL: Test_e2e (2.06s)
/Users/leo/src/golang-sdk/eppoclient/eppoclient_e2e_test.go:141: 
Error Trace:	/Users/leo/src/golang-sdk/eppoclient/eppoclient_e2e_test.go:141
Error:      	Should have called with given arguments
Test:       	Test_e2e
Messages:   	Expected "LogAssignment" to have been called with:
[mock.Anything]
but no actual calls happened
/Users/leo/src/golang-sdk/eppoclient/eppoclient_e2e_test.go:141: 
Error Trace:	/Users/leo/src/golang-sdk/eppoclient/eppoclient_e2e_test.go:141
Error:      	Should have called with given arguments
Test:       	Test_e2e
Messages:   	Expected "LogAssignment" to have been called with:
[mock.Anything]
but no actual calls happened
/Users/leo/src/golang-sdk/eppoclient/eppoclient_e2e_test.go:141: 
Error Trace: …
```

Use mock assignment logger and verify it is being called (FF-1450)

---

Makefile

I am adding a benching suite that will generate a memory profile against main branch and compare it with the feature branch. https://github.com/Eppo-exp/golang-sdk/pull/32
However I am currently blocked as the main branch does not have these two commands and is failing to run.
👉 Adding here to unblock.

add stub makefile commands for memory profiling

---

.github/workflows/memory-profile-compare.yml
.gitignore
Makefile

our customers expect the golang sdk to be performant and have minimal impact on their running server. 
as we are making changes to the golang sdk, we need evaluate those changes for correctness. with this benchmark we will have added information to see about additional memory allocations happening with the proposed branch.
* checks out main branch
* executes `make profile-memory` to produce `memprofile.main.out` (binary) and `memprofile.main.text` (human readible)
```
➜ cat memprofile.main.text
Type: alloc_space
Time: Feb 14, 2024 at 3:54pm (PST)
Showing nodes accounting for 31134.62kB, 100% of 31134.62kB total
Showing top 50 nodes out of 66
flat  flat%   sum%        cum   cum%
8193.70kB 26.32% 26.32% 12801.91kB 41.12%  encoding/json.mapEncoder.encode
3584.20kB 11.51% 37.83%  3584.20kB …
```

Perform memory profiling and comparison benchmarking for pull requests (FF-1563)

---

.github/workflows/memory-profile-compare.yml
eppoclient/client.go
eppoclient/configurationrequestor.go
eppoclient/configurationstore.go
eppoclient/configurationstore_test.go
go.mod
go.sum

Eppo downloads configuration files from its RAC API at regular intervals; this data is cached in local memory.
When serving evaluations they are loaded from the cache.
* When serving evaluations the `GetConfiguration` is performing a redundant `json.Marshall` to convert the stored cache entry into a json string. this allocates memory without meaningful utility.
* The `getAssignment` method performed redundant `json.Marshall` on the assignment logging object.
Overall the "read path" of the SDK was allocating substantial number of objects without obvious value.
Optimizes the "read path" to trust the cached entry and instantiate the `experimentConfiguration` object directly. Shifts json validation to the "write path" which happens in the background and much less frequently, outside of the …

avoid extra json marshal when loading configuration from cache (FF-1564)

---

eppoclient/rules.go
eppoclient/rules_test.go
eppoclient/utils.go
eppoclient/utils_test.go

A behavioral regression took place when creating semver support (https://github.com/Eppo-exp/golang-sdk/commit/5f8765036dafb7927204f204d862ac6f31d8b7f2) wherein subject attribute values in the format `"2"` stopped being coerced into numerics. This led to user confusion as evaluations stopped happening which they depended on.
Both `2` and `"2"` will be treated as numerics (specifically `float64`) for the purposes of comparison evaluation.
The `ToFloat64` function is able to safely handle a variety of input values and return a converted value or an error that the caller much check against.
* new unit tests for `ToFloat64` function
* augmented unit tests for rule evaluation including both numeric and string wrapped numerics

allow subject attributes to be string wrapper numerics; attempt to safely coerce

---

eppoclient/configurationrequestor.go
eppoclient/httpclient.go
eppoclient/httpclient_test.go

When the Eppo API returns an HTTP >= 500, the SDK emits a `log.Fatal`. I believe this was added without fully realizing its side-effect behavior of immediately exiting the program with status 1.
* https://jhall.io/posts/2022-02-26-fatal-logging/
* https://stackoverflow.com/questions/33885235/should-a-go-package-ever-use-log-fatal-and-when
In effect our `http_client.go` library is deciding for the rest of the SDK what behavior an `HTTP 500` response should have. It is best to simply return this information upstream and let the relevant calling code make that determination, otherwise our server SDK customers will have regular process restarts.
* remove all usages of `log.Fatal`
* add an `error` object response to `get` method of `http_client.go`
* adds unit tests for `http_client.go`
The …

Remove usage of log.Fatal from httpclient.go; return an error object instead (FF-1934)

---

eppoclient/client.go
eppoclient/utils.go
eppoclient/utils_test.go

[eppo's documentation](https://docs.geteppo.com/sdks/server-sdks/go/#define-an-assignment-logger-experiment-assignment-only) shows an ISO 8601 date.
the assignment logger provides a timestamp as `2024-05-14 14:56:25.105294 -0700 PDT m=+10.002113084` which does not directly match.
Provide a timestamp in RFC 3339 format.

Assignment timestamp in RFC 3339 format. (FF-2082)

---

README.md
eppoclient/client.go
eppoclient/client_test.go
eppoclient/doc.go
eppoclient/eppoclient_e2e_test.go
eppoclient/initclient.go
go.mod

We forgot to update the ordering of arguments for the `get_assignment` functions -- fixed here

[ufc] update "get_assignment" args ordering to comply with ufc spec

---

Makefile
eppoclient/initclient.go
eppoclient/poller_test.go
eppoclient/rules.go
eppoclient/rules_test.go
eppoclient/utils_test.go

_Eppo Internal_:
🎟️ **Ticket:** [FF-2507 - Boolean variation not returning expected allocation](https://linear.app/eppo/issue/FF-2507/boolean-variation-not-returning-expected-allocation)
🗨️ **Slack:** ["...It seems it's always defaulting to the default allocation..."](https://eppo-group.slack.com/archives/C074S1ZAQH2/p1719265728412039)
When passing in integer attributes (e.g., `attributes: map[attribute1:0 attribute2:1000]` the numeric rules were not matching when they should. This was because our `toFloat64()` utility function was not properly converting.
This pull request changes `toFloat64()` to handle all numeric types.

Fix evaluation of numeric attributes that are not passed in as strings or float64s

---

eppoclient/configurationstore.go
eppoclient/errors.go
eppoclient/evalflags.go
eppoclient/initclient.go

Hi Eppo team,
my team wants to be able to handle the cases where flag is not found/not enabled better and I think it'd be more convenient to define these errors as (public) vars so they can be handled more nicely with `errors.Is( ... )`
thanks!

Return sentinel errors to help handling by callers

---

eppoclient/client.go
eppoclient/configurationstore.go
eppoclient/evalbandits.go
eppoclient/initclient.go

🎟️ fixes FF-3068 FF-3069
Tweaks to the bandit selection algorithm decided after implementation of some SDKs has led to some falling behind in feature/fix parity. The SDK test data repository tests each SDK, but within its own workflows, so when new tests break the SDK, it stays green until a new PR.
- When two actions have the same high score, pick the smaller one, lexicographically
- When evaluating bandits, compute the string assignment, then check whether any actions were passed. 
Passing!

fix: Handle empty actions list and high-score tiebreaking

---

.gitignore
eppoclient/applicationlogger/interface.go
eppoclient/applicationlogger/scrubbing_logger.go
eppoclient/applicationlogger/zap_logger.go
eppoclient/client.go
eppoclient/utils_test.go

Also changed some logging calls for error states which were incorrectly using `info`

fix: Properly use templated version of logging calls

---

eppoclient/client_test.go
eppoclient/evalflags.go

* Customer started an experiment with 1% percent exposure.
* They saw 100x the assignment volume
After investigating the cause, found that the default allocation was responsible for the overage. We should not be logging these events.
🎫 https://linear.app/eppo/issue/FF-3109/kargo-experiment-generated-much-more-exposures-than-expected
Only log when `DoLog` on an allocation is explicitly `true`

bug: [Do not log assignment when DoLog is absent or not explicitly true] (FF-3109)

---

eppoclient/lruassignmentlogger.go
eppoclient/lruassignmentlogger_test.go

`LruAssignmentLogger` did not have `LogBanditAction` which means it was masking the bandit logger of the inner logger

fix: proxy LogBanditAction through LruAssignmentLogger

---

.github/workflows/test.yml

🎟️ Fixes FF-3087 towards FF-3085
👯‍♂️ **Related PRs**
- [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data/pull/59)
- [react-native-sdk](https://github.com/Eppo-exp/react-native-sdk/pull/58)
- [ios-sdk](https://github.com/Eppo-exp/eppo-ios-sdk/pull/40)
- [android-sdk](https://github.com/Eppo-exp/android-sdk/pull/93)
Changes are often made to the [sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) repository to capture new behaviours, bugs and edge cases. When these changes are pushed to `main`, the SDKs are cloned locally (locally to the github action running) and their respective tests are run. These tests are set up and run by copies of the SDK test workflows - see [sdk-test-data workflow](https://github.com/Eppo-exp/sdk-test-data/blob/main/.github/workflows/test-sdks.yml). …

quality: parameterize sdk and test data branches

---

README.md
eppoclient/initclient.go
eppoclient/version.go
go.mod

A breaking API change was made since the last minor release; creating `v6`.

release v6

---

eppoclient/config.go
eppoclient/initclient.go

_Eppo Internal:_
[//]: #  (Link to the issue corresponding to this chunk of work)
:tickets: Fixes #74 
:scroll: Design Doc: __link if applicable__
[//]: #  (Why is this change required? What problem does it solve?)
To allow tuning the HTTP client, such as TCP transportation config, to fix the issue reported in #74.
[//]: # (Describe your changes in detail)
With this change, when we initialize the Eppo client, we can pass in a custom HTTP client like this:
```
var httpClientInstance *http.Client
httpClientInstance = &http.Client{Timeout: 10 * time.Second}
httpClientInstance.Transport = &http.Transport{
Proxy: http.ProxyFromEnvironment,
DialContext: (&net.Dialer{
Timeout:   5 * time.Second,
KeepAlive: 10 * time.Second,
}).DialContext,
MaxIdleConns:          100,
IdleConnTimeout:       90 * …
```

feat: allow passing custom http client
